### ISSUE TITLE
All P values are same

### ISSUE THREAD

**Issue by rained1989** [laurensvdwiel/SpatialClustering#1] opened 2021-01-19 14:31 UTC
Hello,

Thanks for this great tools. I have some questions about output of SpatialClustering. I ran this tool for some genes with TCGA Pan-Cancer mutations, and got same p value for all genes. My code is :
./SpatialClustering_env/bin/python spatial_clustering/spatial_clustering.py --gene_name=$gene_symbol --variant_cDNA_locations=$list_cDNA_mutation --cDNA_length=$cDNA_length --n_permutations=10 --parallel=True --random_seed=1 --correction=1
The number of cDNA mutation range from 50 to 2000. Could you kindly help me debug? Thanks.

Rained

**Comment by laurensvdwiel** [comment] 2021-01-22 13:01
Hi Rained,

Thank you for your question and your interest.

I cannot fully answer your question without some additional details. Could you provide me with the following:

- What is the value of the p-values that are constantly the same?
- Could you show me the exact input for two seperate calls of the algorithm? Specifically the values for $list_cDNA_mutation and $cDNA_length.

Thank you for contacting me and I will reply to you ASAP if you provide me those details.

- Laurens

**Comment by bopohdr** [comment] 2022-05-24 18:47
Hi Laurens,

I have the same issue - I get the same p values if the number of permutations are the same for different sets of variants. I noticed that p value is much less influenced by location of the variants, but much more by the number of variants

Same number of permutation - different number of variants 


```
~/Downloads/SpatialClustering-master  time SpatialClustering_env/bin/python spatial_clustering/spatial_clustering.py --gene_name=KDM6B --variant_cDNA_locations=138,138,343,403,403,403,419,445,496,523,578,654,654,685,1014,1044,1085,1085,1085,1229,1258,1416,1416,1439,1483,1537,1769,2011,2125,2134,2448,2572,2598,2690,2699,2865,2923,2923,2970,2985,3038,3046,3281,3288,3295,3535,3564,3674,3911,3944,4020,4165,4184,4431,4468,4500,4708,4733,4737,4794 --cDNA_length=4929 --parallel=True --random_seed=1 --correction=1 --n_permutations=1000000
Computing spatial clustering for gene: KDM6B
cDNA_length: 4929
variant_cDNA_locations: ['138', '138', '343', '403', '403', '403', '419', '445', '496', '523', '578', '654', '654', '685', '1014', '1044', '1085', '1085', '1085', '1229', '1258', '1416', '1416', '1439', '1483', '1537', '1769', '2011', '2125', '2134', '2448', '2572', '2598', '2690', '2699', '2865', '2923', '2923', '2970', '2985', '3038', '3046', '3281', '3288', '3295', '3535', '3564', '3674', '3911', '3944', '4020', '4165', '4184', '4431', '4468', '4500', '4708', '4733', '4737', '4794']
Settings: random_seed: 1, parallel: True, n_permutations: 1000000

Results:
gene: KDM6B, with n variants: 60
geometric_mean: 0.0
corrected p-value: 9.99999000001e-07 (Bonferroni correction = 1)



 ~/Downloads/SpatialClustering-master  time SpatialClustering_env/bin/python spatial_clustering/spatial_clustering.py --gene_name=KDM6B --variant_cDNA_locations=138,138,343,403,403,403,419,445,496,523,578,654,654,685,1014,1044,1085,1085,1085,4794 --cDNA_length=4929 --parallel=True --random_seed=1 --correction=1 --n_permutations=1000000
Computing spatial clustering for gene: KDM6B
cDNA_length: 4929
variant_cDNA_locations: ['138', '138', '343', '403', '403', '403', '419', '445', '496', '523', '578', '654', '654', '685', '1014', '1044', '1085', '1085', '1085', '4794']
Settings: random_seed: 1, parallel: True, n_permutations: 1000000

Results:
gene: KDM6B, with n variants: 20
geometric_mean: 3.583556129343602e-11
corrected p-value: 9.99999000001e-07 (Bonferroni correction = 1)



 ~/Downloads/SpatialClustering-master  time SpatialClustering_env/bin/python spatial_clustering/spatial_clustering.py --gene_name=KDM6B --variant_cDNA_locations=3762,3992,4136,4118,4174,4186,4187,4193,4222,4696,4724 --cDNA_length=4929 --parallel=True --random_seed=1 --correction=1 --n_permutations=1000000
Computing spatial clustering for gene: KDM6B
cDNA_length: 4929
variant_cDNA_locations: ['3762', '3992', '4136', '4118', '4174', '4186', '4187', '4193', '4222', '4696', '4724']
Settings: random_seed: 1, parallel: True, n_permutations: 1000000

Results:
gene: KDM6B, with n variants: 11
geometric_mean: 2.2696460054206864e-08
corrected p-value: 9.99999000001e-07 (Bonferroni correction = 1)

SpatialClustering_env/bin/python spatial_clustering/spatial_clustering.py      1474.14s user 91.14s system 895% cpu 2:54.71 total
```

Same number of variants - different number of permutations

```
time SpatialClustering_env/bin/python spatial_clustering/spatial_clustering.py --gene_name=KDM6B --variant_cDNA_locations=3762,3992,4136,4118,4174,4186,4187,4193,4222,4696,4724 --cDNA_length=4929 --parallel=True --random_seed=1 --correction=1 --n_permutations=1000
Computing spatial clustering for gene: KDM6B
cDNA_length: 4929
variant_cDNA_locations: ['3762', '3992', '4136', '4118', '4174', '4186', '4187', '4193', '4222', '4696', '4724']
Settings: random_seed: 1, parallel: True, n_permutations: 1000

Results:
gene: KDM6B, with n variants: 11
geometric_mean: 2.2696460054206864e-08
corrected p-value: 0.000999000999000999 (Bonferroni correction = 1)



 ~/Downloads/SpatialClustering-master  time SpatialClustering_env/bin/python spatial_clustering/spatial_clustering.py --gene_name=KDM6B --variant_cDNA_locations=3762,3992,4136,4118,4174,4186,4187,4193,4222,4696,4724 --cDNA_length=4929 --parallel=True --random_seed=1 --correction=1 --n_permutations=10000
Computing spatial clustering for gene: KDM6B
cDNA_length: 4929
variant_cDNA_locations: ['3762', '3992', '4136', '4118', '4174', '4186', '4187', '4193', '4222', '4696', '4724']
Settings: random_seed: 1, parallel: True, n_permutations: 10000

Results:
gene: KDM6B, with n variants: 11
geometric_mean: 2.2696460054206864e-08
corrected p-value: 9.999000099990002e-05 (Bonferroni correction = 1)



 ~/Downloads/SpatialClustering-master  time SpatialClustering_env/bin/python spatial_clustering/spatial_clustering.py --gene_name=KDM6B --variant_cDNA_locations=3762,3992,4136,4118,4174,4186,4187,4193,4222,4696,4724 --cDNA_length=4929 --parallel=True --random_seed=1 --correction=1 --n_permutations=100000
Computing spatial clustering for gene: KDM6B
cDNA_length: 4929
variant_cDNA_locations: ['3762', '3992', '4136', '4118', '4174', '4186', '4187', '4193', '4222', '4696', '4724']
Settings: random_seed: 1, parallel: True, n_permutations: 100000

Results:
gene: KDM6B, with n variants: 11
geometric_mean: 2.2696460054206864e-08
corrected p-value: 9.99990000099999e-06 (Bonferroni correction = 1)



 ~/Downloads/SpatialClustering-master time SpatialClustering_env/bin/python spatial_clustering/spatial_clustering.py --gene_name=KDM6B --variant_cDNA_locations=3762,3992,4136,4118,4174,4186,4187,4193,4222,4696,4724 --cDNA_length=4929 --parallel=True --random_seed=1 --correction=1 --n_permutations=1000000
Computing spatial clustering for gene: KDM6B
cDNA_length: 4929
variant_cDNA_locations: ['3762', '3992', '4136', '4118', '4174', '4186', '4187', '4193', '4222', '4696', '4724']
Settings: random_seed: 1, parallel: True, n_permutations: 1000000

Results:
gene: KDM6B, with n variants: 11
geometric_mean: 2.2696460054206864e-08
corrected p-value: 9.99999000001e-07 (Bonferroni correction = 1)

```
Not sure that random_seed changes this

```
SpatialClustering_env/bin/python spatial_clustering/spatial_clustering.py --gene_name=KDM6B --variant_cDNA_locations=3762,3992,4136,4118,4174,4186,4187,4193,4222,4696,4724 --cDNA_length=4929 --parallel=True --random_seed=1 --correction=1 --n_permutations=1000000
Computing spatial clustering for gene: KDM6B
cDNA_length: 4929
variant_cDNA_locations: ['3762', '3992', '4136', '4118', '4174', '4186', '4187', '4193', '4222', '4696', '4724']
Settings: random_seed: 1, parallel: True, n_permutations: 1000000

Results:
gene: KDM6B, with n variants: 11
geometric_mean: 2.2696460054206864e-08
corrected p-value: 9.99999000001e-07 (Bonferroni correction = 1)



 SpatialClustering_env/bin/python spatial_clustering/spatial_clustering.py --gene_name=KDM6B --variant_cDNA_locations=3762,3992,4136,4118,4174,4186,4187,4193,4222,4696,4724 --cDNA_length=4929 --parallel=True --random_seed=2 --correction=1 --n_permutations=1000000
Computing spatial clustering for gene: KDM6B
cDNA_length: 4929
variant_cDNA_locations: ['3762', '3992', '4136', '4118', '4174', '4186', '4187', '4193', '4222', '4696', '4724']
Settings: random_seed: 2, parallel: True, n_permutations: 1000000

Results:
gene: KDM6B, with n variants: 11
geometric_mean: 2.2696460054206864e-08
corrected p-value: 9.99999000001e-07 (Bonferroni correction = 1)
```

I can also send a figure with the position of the variants to see the distribution better. 

Thanks,
Dmitrijs

**Comment by laurensvdwiel** [comment] 2022-05-24 19:04
Hi Both, apologies for not seeing this issue sooner.

Could you please confirm that you have set the multiple testing correction right? The Bonferroni correction is in all instances here set to '1' as per the `--correction=1` parameter. In the paper we set the correction to the number of genes in the dataset tested.

**Comment by bopohdr** [comment] 2022-05-24 19:08
Hi ! 

In all tests I used --correction=1 (as provided in test example), as I tested only 1 gene (but two types of variants).

**Comment by laurensvdwiel** [comment] 2022-05-24 19:17
From a statistic perspective I would at least set the correction to the number of times you perform the "test" (e.g. running this code). So for one gene tested with two different variants separately I would set the correction to two.

The geometric mean in all of your cases is so small (e.g. it clusters) that the p value becomes very tiny. Could you share the distribution on the gene as a figure?

**Comment by bopohdr** [comment] 2022-05-24 19:24
<img width="960" alt="image" src="https://user-images.githubusercontent.com/43725393/170115344-f9f8dd7e-b54a-4ace-bc36-d5608de06d8a.png">

Variants in red or orange (We expect that they do not cluster):
```
~/Downloads/SpatialClustering-master  time SpatialClustering_env/bin/python spatial_clustering/spatial_clustering.py --gene_name=KDM6B --variant_cDNA_locations=138,138,343,403,403,403,419,445,496,523,578,654,654,685,1014,1044,1085,1085,1085,1229,1258,1416,1416,1439,1483,1537,1769,2011,2125,2134,2448,2572,2598,2690,2699,2865,2923,2923,2970,2985,3038,3046,3281,3288,3295,3535,3564,3674,3911,3944,4020,4165,4184,4431,4468,4500,4708,4733,4737,4794 --cDNA_length=4929 --parallel=True --random_seed=1 --correction=1 --n_permutations=1000000
Computing spatial clustering for gene: KDM6B
cDNA_length: 4929
variant_cDNA_locations: ['138', '138', '343', '403', '403', '403', '419', '445', '496', '523', '578', '654', '654', '685', '1014', '1044', '1085', '1085', '1085', '1229', '1258', '1416', '1416', '1439', '1483', '1537', '1769', '2011', '2125', '2134', '2448', '2572', '2598', '2690', '2699', '2865', '2923', '2923', '2970', '2985', '3038', '3046', '3281', '3288', '3295', '3535', '3564', '3674', '3911', '3944', '4020', '4165', '4184', '4431', '4468', '4500', '4708', '4733', '4737', '4794']
Settings: random_seed: 1, parallel: True, n_permutations: 1000000

Results:
gene: KDM6B, with n variants: 60
geometric_mean: 0.0
corrected p-value: 9.99999000001e-07 (Bonferroni correction = 1)
```
same variants, but I just cropped the last variants, to test if I would get different results with less variants (when I realised that different variant sets give same p values)

```
 ~/Downloads/SpatialClustering-master  time SpatialClustering_env/bin/python spatial_clustering/spatial_clustering.py --gene_name=KDM6B --variant_cDNA_locations=138,138,343,403,403,403,419,445,496,523,578,654,654,685,1014,1044,1085,1085,1085,4794 --cDNA_length=4929 --parallel=True --random_seed=1 --correction=1 --n_permutations=1000000
Computing spatial clustering for gene: KDM6B
cDNA_length: 4929
variant_cDNA_locations: ['138', '138', '343', '403', '403', '403', '419', '445', '496', '523', '578', '654', '654', '685', '1014', '1044', '1085', '1085', '1085', '4794']
Settings: random_seed: 1, parallel: True, n_permutations: 1000000

Results:
gene: KDM6B, with n variants: 20
geometric_mean: 3.583556129343602e-11
corrected p-value: 9.99999000001e-07 (Bonferroni correction = 1)
```

The variants in blue and purple (clearly cluster at C-term):
```
~/Downloads/SpatialClustering-master  time SpatialClustering_env/bin/python spatial_clustering/spatial_clustering.py --gene_name=KDM6B --variant_cDNA_locations=3762,3992,4136,4118,4174,4186,4187,4193,4222,4696,4724 --cDNA_length=4929 --parallel=True --random_seed=1 --correction=1 --n_permutations=1000000
Computing spatial clustering for gene: KDM6B
cDNA_length: 4929
variant_cDNA_locations: ['3762', '3992', '4136', '4118', '4174', '4186', '4187', '4193', '4222', '4696', '4724']
Settings: random_seed: 1, parallel: True, n_permutations: 1000000

Results:
gene: KDM6B, with n variants: 11
geometric_mean: 2.2696460054206864e-08
corrected p-value: 9.99999000001e-07 (Bonferroni correction = 1)

SpatialClustering_env/bin/python spatial_clustering/spatial_clustering.py      1474.14s user 91.14s system 895% cpu 2:54.71 total
```

the examples are the same as from above.

If I change bonferoni to 2, wouldn't it just give same p value divided by 2 in both cases?

Best,
Dmitrijs

**Comment by bopohdr** [comment] 2022-05-25 08:43
I also tried running the red and orange LoF variants without the recurrent ones, but still p value es completely the same as with recurrent variants.

```
 time SpatialClustering_env/bin/python spatial_clustering/spatial_clustering.py --gene_name=KDM6B --variant_cDNA_locations=138,343,403,419,445,496,523,578,654,685,1014,1044,1085,1229,1258,1416,1439,1483,1537,1769,2011,2125,2134,2448,2572,2598,2690,2699,2865,2923,2970,2985,3038,3046,3281,3288,3295,3535,3564,3674,3911,3944,4020,4165,4184,4431,4468,4500,4708,4733,4737,4794 --cDNA_length=4929 --parallel=True --random_seed=1 --correction=1 --n_permutations=1000000
Computing spatial clustering for gene: KDM6B
cDNA_length: 4929
variant_cDNA_locations: ['138', '343', '403', '419', '445', '496', '523', '578', '654', '685', '1014', '1044', '1085', '1229', '1258', '1416', '1439', '1483', '1537', '1769', '2011', '2125', '2134', '2448', '2572', '2598', '2690', '2699', '2865', '2923', '2970', '2985', '3038', '3046', '3281', '3288', '3295', '3535', '3564', '3674', '3911', '3944', '4020', '4165', '4184', '4431', '4468', '4500', '4708', '4733', '4737', '4794']
Settings: random_seed: 1, parallel: True, n_permutations: 1000000

Results:
gene: KDM6B, with n variants: 52
geometric_mean: 0.0
corrected p-value: 9.99999000001e-07 (Bonferroni correction = 1)
```

**Comment by bopohdr** [comment] 2022-06-14 21:17
> From a statistic perspective I would at least set the correction to the number of times you perform the "test" (e.g. running this code). So for one gene tested with two different variants separately I would set the correction to two.
> 
> The geometric mean in all of your cases is so small (e.g. it clusters) that the p value becomes very tiny. Could you share the distribution on the gene as a figure?

Hi Laurence,

Did figure of the variants helped to identify the cause of the identical p values?

**Comment by laurensvdwiel** [comment] 2022-07-15 18:55
Issue located, the product function at https://github.com/laurensvdwiel/SpatialClustering/blob/master/spatial_clustering/spatial_clustering.py#L74
by default only returns float64/int64 instances, the numbers become too small with large arrays as in this thread. I now fixed it to allow float128 dtype expectancy in: [ec3427d](https://github.com/laurensvdwiel/SpatialClustering/commit/ec3427da259a7ef3dbe399052605d70ace14de27)

**Closed as completed by laurensvdwiel** 2022-07-15 18:55 UTC
